apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 25565
      targetPort: 25565
  selector:
    app: minecraft-server