name: Deploy Cloud Functions

on:
  push:
    tags:
      - "v*"

jobs:
  job_id:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider:  ${{ secrets.FUNCTIONS_IP }}
        service_account: ${{ secrets.FUNCTIONS_SERVICE_ACCOUNT }}
    - uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: ${{ vars.FUNCTIONS_NAME }}
        runtime: python311
        entry_point: "manage"
        region: asia-northeast1
        source_dir: "functions"
        env_vars: |
          OWNER=${{ github.repository_owner }},REPOSITORY=${{ github.repository }},ENV=pro,DEPLOYMENT_FILE_NAME=deployment.yml,LOADBALANCER_FILE_NAME=loadbalancer.yml,DEPLOYMENT_FILE_PATH=/tmp,LOADBALANCER_FILE_PATH="/tmp",POD_LABEL=minecraft-server,LOADBALANCER_NAME=minecraft-lb,SERVICE_NAMESPACE=default,DEPLOYMENT_NAMESPACE=default,CLUSTER_NAME=${{ secrets.CLUSTER_NAME }},REGION=${{ vars.REGION }},PROJECT_ID=${{ secrets.PROJECT_ID }}
        service_account_email: ${{ secrets.FUNCTIONS_SERVICE_ACCOUNT }}