name: Build and upload image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        env:
          TAG_NAME: ${{ GITHUB_REPOSITORY }}
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.TAG_NAME }}:latest
            ghcr.io/${{ env.TAG_NAME }}:${GITHUB_REF#refs/*/}
