name: Build create job image

on:
  push:
    tags:
      - "v*"

jobs:
  job_id:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - id: "auth"
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: "access_token"
        workload_identity_provider:  ${{ secrets.FUNCTIONS_IP }}
        service_account: ${{ secrets.FUNCTIONS_SERVICE_ACCOUNT }}
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: asia.gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/build-push-action@v3
      with:
        context: ./deploy-job
        file: deploy-job/python-gcloud-k8s-client-create.Dockerfile
        push: true
        tags: |
          asia.gcr.io/${{ secrets.PROJECT_ID }}/python-gcloud-k8s-client-create:latest
          asia.gcr.io/${{ secrets.PROJECT_ID }}/python-gcloud-k8s-client-create:${{ github.ref_name }}